# postgresqlの設定

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  database: rails_exam01_development

test:
  <<: *default
  database: rails_exam01__test

production:
  <<: *default
  database: rails_exam01_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>